"""Auto-generated custom tool: bmi_calculator

Description: Calculate Body Mass Index (BMI) from height and weight
Created: 2026-01-18T18:34:03.961262
Status: pending

WARNING: This file was auto-generated by ToolBuilderTool.
Do not edit manually unless you know what you're doing.
"""

import json
import re
from datetime import datetime, timedelta
from typing import Any, Optional
import math
import random
import hashlib
import base64
from urllib.parse import urlencode, quote, unquote



class BmiCalculatorTool:
    """Calculate Body Mass Index (BMI) from height and weight"""

    def __init__(self):
        self.name = "bmi_calculator"
        self.description = "Calculate Body Mass Index (BMI) from height and weight"

    def calculate_bmi(self, weight_kg: Any, height_m: Any) -> dict:
        """Calculate BMI from weight in kg and height in meters

        Args:
            weight_kg: Parameter weight_kg
            height_m: Parameter height_m

        Returns:
            Result dictionary with success status and data
        """
        try:
            weight = float(weight_kg)
            height = float(height_m)
            bmi = weight / (height ** 2)
            category = 'Underweight' if bmi < 18.5 else 'Normal' if bmi < 25 else 'Overweight' if bmi < 30 else 'Obese'
            return {"success": True, "bmi": round(bmi, 1), "category": category}
        except Exception as e:
            return {"success": False, "error": str(e)}

    def calculate_bmi_imperial(self, weight_lbs: Any, height_inches: Any) -> dict:
        """Calculate BMI from weight in pounds and height in inches

        Args:
            weight_lbs: Parameter weight_lbs
            height_inches: Parameter height_inches

        Returns:
            Result dictionary with success status and data
        """
        try:
            weight = float(weight_lbs)
            height = float(height_inches)
            bmi = (weight * 703) / (height ** 2)
            category = 'Underweight' if bmi < 18.5 else 'Normal' if bmi < 25 else 'Overweight' if bmi < 30 else 'Obese'
            return {"success": True, "bmi": round(bmi, 1), "category": category}
        except Exception as e:
            return {"success": False, "error": str(e)}


    def _extract_param(self, action: str, param_name: str, index: int) -> Any:
        """Extract a parameter from the action string."""
        import re
        # Try to find named parameter
        pattern = rf'{param_name}[=:]\s*["\'"]?([^"\'"\s]+)["\'"]?'
        match = re.search(pattern, action, re.IGNORECASE)
        if match:
            return match.group(1)
        # Try to extract by position from quoted strings
        quoted = re.findall(r'["\'"]([^"\'"]+)["\'"]', action)
        if index < len(quoted):
            return quoted[index]
        # Try to extract numbers
        numbers = re.findall(r'\b\d+(?:\.\d+)?\b', action)
        if index < len(numbers):
            return numbers[index]
        return None


    def execute(self, action: str) -> dict:
        """Execute an action on this tool.

        Args:
            action: The action string to parse and execute

        Returns:
            Result dictionary with success status and data
        """
        action_lower = action.lower()

        if "calculate_bmi" in action_lower:
            weight_kg = self._extract_param(action, "weight_kg", 0)
            height_m = self._extract_param(action, "height_m", 1)
            return self.calculate_bmi(weight_kg, height_m)

        if "calculate_bmi_imperial" in action_lower:
            weight_lbs = self._extract_param(action, "weight_lbs", 0)
            height_inches = self._extract_param(action, "height_inches", 1)
            return self.calculate_bmi_imperial(weight_lbs, height_inches)


        return {"success": False, "error": f"Unknown action: {action}"}
