"""Auto-generated custom tool: temperature_converter

Description: Convert temperatures between Celsius and Fahrenheit
Created: 2026-01-18T18:50:47.041375
Status: pending

WARNING: This file was auto-generated by ToolBuilderTool.
Do not edit manually unless you know what you're doing.
"""

import json
import re
from datetime import datetime, timedelta
from typing import Any, Optional
import math
import random
import hashlib
import base64
from urllib.parse import urlencode, quote, unquote



class TemperatureConverterTool:
    """Convert temperatures between Celsius and Fahrenheit"""

    def __init__(self):
        self.name = "temperature_converter"
        self.description = "Convert temperatures between Celsius and Fahrenheit"

    def celsius_to_fahrenheit(self, celsius: Any) -> dict:
        """Convert Celsius to Fahrenheit

        Args:
            celsius: Parameter celsius

        Returns:
            Result dictionary with success status and data
        """
        try:
            temp = float(celsius)
            fahrenheit = (temp * 9/5) + 32
            return {"success": True, "fahrenheit": round(fahrenheit, 2)}
        except Exception as e:
            return {"success": False, "error": str(e)}

    def fahrenheit_to_celsius(self, fahrenheit: Any) -> dict:
        """Convert Fahrenheit to Celsius

        Args:
            fahrenheit: Parameter fahrenheit

        Returns:
            Result dictionary with success status and data
        """
        try:
            temp = float(fahrenheit)
            celsius = (temp - 32) * 5/9
            return {"success": True, "celsius": round(celsius, 2)}
        except Exception as e:
            return {"success": False, "error": str(e)}


    def _extract_param(self, action: str, param_name: str, index: int) -> Any:
        """Extract a parameter from the action string."""
        import re
        # Try to find named parameter
        pattern = rf'{param_name}[=:]\s*["\'"]?([^"\'"\s]+)["\'"]?'
        match = re.search(pattern, action, re.IGNORECASE)
        if match:
            return match.group(1)
        # Try to extract by position from quoted strings
        quoted = re.findall(r'["\'"]([^"\'"]+)["\'"]', action)
        if index < len(quoted):
            return quoted[index]
        # Try to extract numbers
        numbers = re.findall(r'\b\d+(?:\.\d+)?\b', action)
        if index < len(numbers):
            return numbers[index]
        return None


    def execute(self, action: str) -> dict:
        """Execute an action on this tool.

        Args:
            action: The action string to parse and execute

        Returns:
            Result dictionary with success status and data
        """
        action_lower = action.lower()

        if "celsius_to_fahrenheit" in action_lower:
            celsius = self._extract_param(action, "celsius", 0)
            return self.celsius_to_fahrenheit(celsius)

        if "fahrenheit_to_celsius" in action_lower:
            fahrenheit = self._extract_param(action, "fahrenheit", 0)
            return self.fahrenheit_to_celsius(fahrenheit)


        return {"success": False, "error": f"Unknown action: {action}"}
